version: '3.9'

services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1812
      POSTGRES_DB: notes
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - notesapi-network
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - /etc/letsencrypt:/etc/letsencrypt:ro
    depends_on:
      web:
        condition: service_healthy
    networks:
      - notesapi-network
  web:
    build: .
    restart: on-failure
    command: > 
      sh -c 
      "python manage.py makemigrations &&
      python manage.py migrate &&
      gunicorn settings.wsgi:application --bind 0.0.0.0:8000"
    volumes:
      - .:/django-app
    expose:
      - 8000
    depends_on:
      - db
    environment:
      DB_NAME: notes
      DB_USER: postgres
      DB_PASSWORD: 1812
      DB_HOST: db
      DB_PORT: 5432
    networks:
      - notesapi-network
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8000/" ]
      interval: 5s
      retries: 5
      start_interval: 10s
      timeout: 3s
networks:
  notesapi-network:
    driver: bridge
volumes:
  postgres_data: